name: Frontend Pipeline - CI/CD

on:
  push:
    branches: [ main, develop, 'feature/**' ]
    paths:
      - 'week08/frontend/**'
      - '.github/workflows/frontend-pipeline.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'week08/frontend/**'

env:
  NODE_VERSION: '18'
  FRONTEND_DIR: 'week08/frontend'
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.FRONTEND_DIR }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run lint (if exists)
        run: |
          if npm run lint --dry-run >/dev/null 2>&1; then
            npm run lint
          fi

      - name: Run tests (if exists)
        run: |
          if npm run test --dry-run >/dev/null 2>&1; then
            npm run test
          fi

  build-and-push:
    needs: test-frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.FRONTEND_DIR }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ env.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          TAG="frontend-${{ env.IMAGE_TAG }}"
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/$TAG .
          docker push ${{ env.ACR_LOGIN_SERVER }}/$TAG

      - name: Logout from Azure
        run: az logout
        if: always()

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.CLUSTER_NAME }} \
            --overwrite-existing

      - name: Deploy Frontend
        run: |
          cd k8s
          IMAGE_TAG="frontend-${{ env.IMAGE_TAG }}"
          sed -i "s|latest|$IMAGE_TAG|g" frontend.yaml
          kubectl apply -f frontend.yaml

      - name: Logout from Azure
        run: az logout
        if: always()
