name: Frontend Pipeline - CI/CD

on:
  push:
    branches: [ main, develop, 'feature/**' ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-pipeline.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'

env:
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}
  NODE_VERSION: '18'

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies, lint, and test
        working-directory: frontend
        run: |
          if [ -f package-lock.json ]; then
            npm ci
            if npm run lint --dry-run 2>/dev/null; then npm run lint; fi
            if npm run test --dry-run 2>/dev/null; then npm run test; fi
          else
            echo "No package-lock.json found in frontend/, skipping npm steps"
          fi

  build-frontend:
    needs: test-frontend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Push Frontend Image
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            TAG="prod-${{ env.IMAGE_TAG }}"
          else
            TAG="staging-${{ env.IMAGE_TAG }}"
          fi
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:$TAG ./frontend/
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:$TAG

      - name: Logout from Azure
        run: az logout
        if: always()

  deploy-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS Context
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.CLUSTER_NAME }} \
            --overwrite-existing

      - name: Deploy Frontend
        run: |
          cd k8s/
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            TAG="prod-${{ env.IMAGE_TAG }}"
          else
            TAG="staging-${{ env.IMAGE_TAG }}"
          fi
          sed -i "s|latest|$TAG|g" frontend.yaml
          kubectl apply -f frontend.yaml

      - name: Logout from Azure
        run: az logout
        if: always()
