name: Frontend Pipeline - CI/CD

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
    paths:
      - 'week08/frontend/**'
      - '.github/workflows/frontend-pipeline.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'week08/frontend/**'

env:
  NODE_VERSION: '18'
  FRONTEND_DIR: week08/frontend
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show repo structure
        run: ls -R

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.FRONTEND_DIR }}/package-lock.json

      - name: Install dependencies
        run: |
          if [ -f ${{ env.FRONTEND_DIR }}/package-lock.json ]; then
            npm ci --prefix ${{ env.FRONTEND_DIR }}
          else
            npm install --prefix ${{ env.FRONTEND_DIR }}
          fi

      - name: Run lint (if exists)
        run: |
          if npm run lint --prefix ${{ env.FRONTEND_DIR }} --dry-run >/dev/null 2>&1; then
            npm run lint --prefix ${{ env.FRONTEND_DIR }}
          fi

      - name: Run tests (if exists)
        run: |
          if npm run test --prefix ${{ env.FRONTEND_DIR }} --dry-run >/dev/null 2>&1; then
            npm run test --prefix ${{ env.FRONTEND_DIR }}
          fi

  build-and-push:
    needs: frontend-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ env.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          TAG=$([[ "${{ github.ref }}" == "refs/heads/main" ]] && echo "prod-${{ env.IMAGE_TAG }}" || echo "staging-${{ env.IMAGE_TAG }}")
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:$TAG ${{ env.FRONTEND_DIR }}
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:$TAG

      - name: Logout Azure
        run: az logout
        if: always()

  deploy-frontend:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS Context
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.CLUSTER_NAME }} \
            --overwrite-existing

      - name: Deploy Frontend to AKS
        run: |
          TAG=$([[ "${{ github.ref }}" == "refs/heads/main" ]] && echo "prod-${{ env.IMAGE_TAG }}" || echo "staging-${{ env.IMAGE_TAG }}")
          sed -i "s|latest|$TAG|g" k8s/frontend.yaml
          kubectl apply -f k8s/frontend.yaml

      - name: Logout Azure
        run: az logout
        if: always()
